Switch to Meson
elementary/cerbere pull request #19
Opened 2018-05-24 16:26 UTC by codygarver

2018-05-24 16:32 UTC, codygarver commented
I have ordered these commits as intended for master, please push them to master instead of squash merging.

2018-05-24 16:57 UTC, codygarver commented
Closes #18

2018-05-24 16:57 UTC, codygarver commented
Closes #3

2018-05-28 22:29 UTC, danirabbit requested changes
It looks like you're missing the post install for compiling schemas and you missed RDNNing the binary name in the README. Otherwise this compiles and appears to install things to places.

2018-05-28 22:29 UTC, danrabbit commented on README.md
>      cerbere
Missed one for RDNN :)

2018-05-28 23:03 UTC, danirabbit approved these changes
LGTM

2018-05-28 23:11 UTC, merged